FROM ubuntu:latest

# First ENTRYPOINT - this will be ignored
ENTRYPOINT ["echo", "Hello from first ENTRYPOINT"]

# First CMD - this will be ignored
CMD ["first CMD"]

# Second ENTRYPOINT - this will be used
ENTRYPOINT ["echo", "Hello from second ENTRYPOINT"]

# Second CMD - this will be used
CMD ["second CMD"]
